### PR TITLE
removed elemento, because it's not supported anymore

### PR DESCRIPTION
**Pull request by treblereel**

### CODE REVIEW

**Comment by hpehl** [comment]
@treblereel has elemento been merged into crysknife?

**Comment by treblereel** [comment]
@hpehl nope, it was used in templates and navigation ... and it was depends on old elemental2 

i hope, i can revert it once it ll be updated

**Comment by treblereel** [comment]
@hpehl elemento dom utilites and builders

**Comment by hpehl** [comment]
Let me know if you'd need help!

**Comment by hpehl** [comment]
I can try to release a new elemento version. What exactly needs to be updated?

**Comment by treblereel** [comment]
@hpehl i think it could be nice to bump elemental2 deps to the latest 1.1.0

**Comment by hpehl** [comment]
The latest elemento release ([1.0.3])(https://search.maven.org/artifact/org.jboss.elemento/elemento-core/1.0.3/jar) depends on elemental2 1.1.0. Anything else which needs to be updated?

**Comment by hpehl** [comment]
Updated Elemento to [1.0.7](https://github.com/hal/elemento/releases/tag/v1.0.7). So please consider adding Elemento again. Thanks!

**Comment by hpehl** [comment]
Just released Elemento 1.0.10 which is the most recent one. Please consider using this version.

**Pull request merged**
